jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --bind_ip_all
    steps:
    - name: Клонирование
      uses: actions/checkout@v3

    - name: Установка Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Установка зависимостей
      run: |
        pip install flask pymongo bcrypt pytest

    - name: Запуск тестов
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest
